version: '3'

services:

  redis:
    image: redis
    ports:
      - '6379:6379'

  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: '$DB_USER'
      POSTGRES_DB: '$DB_NAME'
      POSTGRES_PASSWORD: '$DB_PASSWORD'
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/notify_service
    depends_on:
      db:
        condition: service_healthy


  celery:
    build: .
    tty: true
    command: celery -A notify_service worker -l INFO
    depends_on:
      - redis
      - app

volumes:
  pg_data:
