# Generated by Django 5.1.7 on 2025-05-14 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('scheduled_time', models.DateTimeField(verbose_name='Scheduled time')),
                ('delay', models.PositiveSmallIntegerField(choices=[(0, 'Отправить сейчас'), (1, 'Отправить через час'), (2, 'Отправить через день')], default=0, verbose_name='Delay')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
