# Generated by Django 5.1.7 on 2025-05-15 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('success', 'Успешно'), ('failed', 'Не удалось')], default='success', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='error')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='notify.notification', verbose_name='notification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_logs', to='notify.recipient', verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'delivery_log',
                'verbose_name_plural': 'delivery_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
